server:
  port: 8888
  servlet:
    context-path: /order-mgmt

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kn-order-mgmt-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true
    hibernate:
      ddl-auto: update